-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 11:03:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema social
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`Proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Proveidor` (
  `idProveidor` INT NOT NULL AUTO_INCREMENT,
  `nomProv` VARCHAR(45) NOT NULL,
  `AdressProv` VARCHAR(100) NULL,
  `codiPostal` VARCHAR(8) NULL,
  `ciutatProv` VARCHAR(45) NULL,
  `PaisProv` VARCHAR(45) NULL,
  `TlfProv` VARCHAR(15) NULL,
  `FaxProv` VARCHAR(15) NULL,
  `NIF` VARCHAR(9) NULL,
  PRIMARY KEY (`idProveidor`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Marques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Marques` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nomMarca` VARCHAR(45) NOT NULL,
  `idProveidor` INT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `proveidorsmarques_idx` (`idProveidor` ASC),
  CONSTRAINT `proveidorsmarques`
    FOREIGN KEY (`idProveidor`)
    REFERENCES `optica`.`Proveidor` (`idProveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Colors` (
  `idColor` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColor`),
  UNIQUE INDEX `color_UNIQUE` (`color` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Ulleres` (
  `idUllera` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(65) NOT NULL,
  `idMarca` INT NOT NULL,
  `montura` ENUM('flotant', 'pasta', 'metalica') NULL,
  `graduacio` VARCHAR(50) NULL,
  `idcolormontura` INT NULL,
  `idcolorvidre` INT NULL,
  `preu` DECIMAL(5,2) NULL,
  PRIMARY KEY (`idUllera`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC),
  INDEX `marcaullera_idx` (`idMarca` ASC),
  INDEX `colorullera_idx` (`idcolormontura` ASC),
  INDEX `colorvidre_idx` (`idcolorvidre` ASC),
  CONSTRAINT `marcaullera`
    FOREIGN KEY (`idMarca`)
    REFERENCES `optica`.`Marques` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colorullera`
    FOREIGN KEY (`idcolormontura`)
    REFERENCES `optica`.`Colors` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colorvidre`
    FOREIGN KEY (`idcolorvidre`)
    REFERENCES `optica`.`Colors` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`localitats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`localitats` (
  `idLocalitat` INT NOT NULL AUTO_INCREMENT,
  `localitat` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalitat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `cognomClient` VARCHAR(45) NOT NULL,
  `nomClient` VARCHAR(45) NOT NULL,
  `direccio1` VARCHAR(70) NULL,
  `codiPostal` VARCHAR(6) NULL,
  `idlocalitat` INT NULL,
  `telefon` VARCHAR(15) NULL,
  `email` VARCHAR(60) NULL,
  `dataRegistre` DATE NULL,
  INDEX `localitatclient_idx` (`idlocalitat` ASC),
  PRIMARY KEY (`idClient`),
  CONSTRAINT `localitatclient`
    FOREIGN KEY (`idlocalitat`)
    REFERENCES `optica`.`localitats` (`idLocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Empleats` (
  `idEmpleat` INT NOT NULL AUTO_INCREMENT,
  `cognomEmpl` VARCHAR(45) NOT NULL,
  `nomEmpl` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Vendes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Vendes` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idUllera` INT NOT NULL,
  `Data` DATETIME NULL,
  `idEmpleat` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `vendaclient_idx` (`idClient` ASC),
  INDEX `vendaullera_idx` (`idUllera` ASC),
  INDEX `vendaempleat_idx` (`idEmpleat` ASC),
  CONSTRAINT `vendaclient`
    FOREIGN KEY (`idClient`)
    REFERENCES `optica`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vendaullera`
    FOREIGN KEY (`idUllera`)
    REFERENCES `optica`.`Ulleres` (`idUllera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vendaempleat`
    FOREIGN KEY (`idEmpleat`)
    REFERENCES `optica`.`Empleats` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Recomanacions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Recomanacions` (
  `idClient` INT NOT NULL,
  `idRecomanador` INT NOT NULL,
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC),
  INDEX `client_recomanador_idx` (`idRecomanador` ASC),
  CONSTRAINT `client_recomanat`
    FOREIGN KEY (`idClient`)
    REFERENCES `optica`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `client_recomanador`
    FOREIGN KEY (`idRecomanador`)
    REFERENCES `optica`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
